"""
liquidsoap.py — Liquidsoap integration for TUNE/TWERKER
Generates Liquidsoap scripts and controls via telnet API.
"""
import json, socket, time
from pathlib import Path

_cfg = json.loads(Path("config.json").read_text())
_liq = _cfg["liquidsoap"]

# ── Telnet control ───────────────────────────────────────────────────────────

class LiquidsoapClient:
    def __init__(self):
        self.host = _liq["host"]
        self.port = _liq["port"]

    def _cmd(self, command: str, timeout: float = 3.0) -> str:
        try:
            with socket.create_connection((self.host, self.port), timeout=timeout) as s:
                s.sendall((command + "\n").encode())
                time.sleep(0.1)
                response = b""
                s.settimeout(timeout)
                while True:
                    try:
                        chunk = s.recv(4096)
                        if not chunk:
                            break
                        response += chunk
                        if b"END" in response:
                            break
                    except socket.timeout:
                        break
            return response.decode(errors="replace").strip()
        except (ConnectionRefusedError, OSError) as e:
            return f"ERROR: {e}"

    def skip(self) -> str:
        return self._cmd("squirrelfm.skip")

    def status(self) -> str:
        return self._cmd("squirrelfm.status")

    def push(self, path: str) -> str:
        return self._cmd(f"squirrelfm.push {path}")

    def set_volume(self, vol: float) -> str:
        """vol: 0.0 to 1.0"""
        return self._cmd(f"squirrelfm_vol.set {vol:.2f}")

    def now_playing(self) -> str:
        return self._cmd("request.on_air")

    def queue_remaining(self) -> str:
        return self._cmd("request.queue")

    def is_connected(self) -> bool:
        result = self._cmd("help", timeout=1.0)
        return not result.startswith("ERROR")


liq = LiquidsoapClient()

# ── Script generator ─────────────────────────────────────────────────────────

def generate_liquidsoap_script(
    icecast_host: str,
    icecast_port: int,
    icecast_password: str,
    mount_point: str,
    stream_name: str,
    bitrate: int = 128,
    sample_rate: int = 44100,
) -> str:
    """
    Generate a Liquidsoap script for Squirrel FM.
    Uses a request queue fed by TUNE/TWERKER.
    """
    return f'''#!/usr/bin/liquidsoap
# Squirrel FM — Liquidsoap playout script
# Generated by TUNE/TWERKER
# GPL v3 — No ads. Ever.

set("log.level", 3)
set("log.file", true)
set("log.file.path", "/var/log/liquidsoap/squirrelfm.log")
set("server.telnet", true)
set("server.telnet.bind_addr", "127.0.0.1")
set("server.telnet.port", {_liq["port"]})

# ── Request queue fed by T/T ─────────────────────────────────────────────────
squirrelfm = request.queue(id="squirrelfm")

# ── Fallback: silence if queue runs dry ──────────────────────────────────────
safe = fallback(track_sensitive=false, [squirrelfm, blank()])

# ── Volume control ───────────────────────────────────────────────────────────
squirrelfm_vol = amplify(1.0, id="squirrelfm_vol", override="liq_amplify", safe)

# ── ReplayGain normalisation ──────────────────────────────────────────────────
normalised = amplify(1., id="normalised",
    override="liq_amplify",
    squirrelfm_vol)

# ── Master bus limiter (mandatory — cannot be bypassed) ──────────────────────
limited = normalize(target=0., window=0.03,
    gain_min=-6., gain_max=0.,
    normalised)

# ── Now Playing metadata ──────────────────────────────────────────────────────
def on_meta(m) =
  if m["artist"] != "" then
    log("NOW PLAYING: #{{m["artist"]}} - #{{m["title"]}}")
  end
end

limited = on_metadata(on_meta, limited)

# ── Icecast output ────────────────────────────────────────────────────────────
output.icecast(
  %mp3(bitrate={bitrate}, samplerate={sample_rate}, stereo=true),
  id="icecast_out",
  host="{icecast_host}",
  port={icecast_port},
  password="{icecast_password}",
  mount="{mount_point}",
  name="{stream_name}",
  description="Powered by TUNE/TWERKER",
  public=false,
  limited
)
'''

def write_liquidsoap_script(**kwargs) -> bool:
    script = generate_liquidsoap_script(**kwargs)
    Path(_liq["script_path"]).write_text(script)
    return True
